---
application:
  name: "InnexiaMusic"
  project: "InnexiaMusic"
  organization: "QoveryCommunity"
routers:
- name: "main-innexiamusic"
  routes:
  - application_name: "innexiamusic"
    paths:
    - "/*"
